aruco_code_tracker:
  ros__parameters:
    image_topics:
      - "/static_camera/overhead_cam/color/image_raw"
    camera_info_topics:
      - "/static_camera/overhead_cam/color/camera_info"
    camera_names:
      - "overhead_cam"
    marker_size: 0.10
    aruco_dictionary: 0  # DICT_4X4_50
    marker_id: -1  # -1 = track all detected markers
    marker_frame_id: "aruco_code"
    publish_debug_images: true
