# MoveIt uses this configuration for controller management (simulation)

trajectory_execution:
  allowed_execution_duration_scaling: 2.5
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_gripper_controller
    - right_gripper_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan
      - left_shoulder_lift
      - left_elbow_flex
      - left_wrist_flex
      - left_wrist_roll
    action_ns: follow_joint_trajectory
    default: true

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan
      - right_shoulder_lift
      - right_elbow_flex
      - right_wrist_flex
      - right_wrist_roll
    action_ns: follow_joint_trajectory
    default: true

  left_gripper_controller:
    type: GripperCommand
    joints:
      - left_gripper
    action_ns: gripper_cmd
    default: true

  right_gripper_controller:
    type: GripperCommand
    joints:
      - right_gripper
    action_ns: gripper_cmd
    default: true
