# This config file is used by ros2_control (simulation, global namespace)
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_pan
      - left_shoulder_lift
      - left_elbow_flex
      - left_wrist_flex
      - left_wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_pan
      - right_shoulder_lift
      - right_elbow_flex
      - right_wrist_flex
      - right_wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_gripper_controller:
  ros__parameters:
    joints:
      - left_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_gripper_controller:
  ros__parameters:
    joints:
      - right_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
