# Soft joint limits — used by MoveIt for planning (can override URDF limits)
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  shoulder_pan:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  shoulder_lift:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  elbow_flex:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  wrist_flex:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  wrist_roll:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  gripper:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 0.0
